image: Visual Studio 2017

branches:
  only:
    - master

init:
  - git config --global core.autocrlf true

build_script:
  - ps: .\build.ps1 -Target "AppVeyor"

before_build:
  - choco install opencover.portable
  - choco install codecov

build:
  project: src/OpenSage.sln
  verbosity: minimal
artifacts:
- path: src\OpenSage.Viewer\bin\Release\netcoreapp2.0
  name: Data Viewer
- path: src\OpenSage.Launcher\bin\Release\netcoreapp2.0
  name: Launcher

test_script:
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full C:\projects\opensage\src\OpenSage.Game.Tests\OpenSage.Game.Tests.csproj" -filter:"+[OpenSage*]* -[*.Tests*]*" -oldStyle -output:".\OpenSage_coverage.xml"
  - codecov -f "OpenSage_coverage.xml

test: off

cache:
- tools -> build.cake